### ISSUE TITLE
Off Topic

### ISSUE THREAD

**Issue by ccrvlh** [skwee357/dotfiles#1]
Hey mate, how are you?

I saw your question on DBA Exchange about Double Entry accounting, and this was the only way I found to get in touch with you, hope you don't mind.

I'm developing a double entry system for my personal finances, and if you don't mind, would like to have a chat with you to exchange some ideas. I've designed my DB as single row also, but wanted to understand how you've tackled some challenges like: Accounts Payables/Receivables and the main statements reporting (IS, BS and CF).

Let me know if you would be interested to talk about it.

Cheers, best regards.

**Comment by ccrvlh** [comment]
BTW, here's a bit of my code... It has some scripts to retrieve the Chart Of Accounts, the Income Statement, and the Balance Sheet. You can also find the create tables code with the Chart Of Accounts table and the Journal Table.
https://github.com/lowercase00/finp

**Comment by skwee357** [comment]
Hey @lowercase00, hit me by email we can continue there ko.dmitri@gmail.com
